[tool.black]
line-length = 100
target-version = ["py311", "py312"]

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
force_sort_within_sections = true
known_first_party = ["clipboard_commander"]
skip_glob = ["*/__init__.py"]
